module.exports = {
  PLATFORM_COMMISSION_RATE: 0.07, // 7%
  DEFAULT_DEPOSIT_PERCENT: 0.10,  // 10%
  MIN_DEPOSIT_PERCENT: 0.05,       // 5%
  MAX_DEPOSIT_PERCENT: 0.15,       // 15%
  REFUND_DELAY_HOURS: 72,
  MAX_ACTIVE_GROUPS_PER_USER: 3,
  MIN_TRUST_SCORE: 80,
  DEFAULT_PAGE_SIZE: 20,
  MAX_PAGE_SIZE: 100,
  OTP_LENGTH: 6,
  CURRENCY: 'XOF',

  ROLES: {
    VISITOR: 'VISITOR',
    MEMBER: 'MEMBER',
    SUPPLIER: 'SUPPLIER',
    GROUP_LEADER: 'GROUP_LEADER',
    ADMIN: 'ADMIN',
  },

  GROUP_STATUS: {
    OPEN: 'OPEN',
    THRESHOLD_REACHED: 'THRESHOLD_REACHED',
    CLOSED: 'CLOSED',
    FAILED: 'FAILED',
    CANCELLED: 'CANCELLED',
  },

  PAYMENT_STATUS: {
    PENDING: 'PENDING',
    COMPLETED: 'COMPLETED',
    FAILED: 'FAILED',
    REFUNDED: 'REFUNDED',
    ESCROWED: 'ESCROWED',
  },

  ERROR_CODES: {
    VALIDATION_ERROR: 'VALIDATION_ERROR',
    UNAUTHORIZED: 'UNAUTHORIZED',
    FORBIDDEN: 'FORBIDDEN',
    NOT_FOUND: 'NOT_FOUND',
    CONFLICT: 'CONFLICT',
    INSUFFICIENT_BALANCE: 'INSUFFICIENT_BALANCE',
    GROUP_FULL: 'GROUP_FULL',
    GROUP_CLOSED: 'GROUP_CLOSED',
    ALREADY_MEMBER: 'ALREADY_MEMBER',
    THRESHOLD_REACHED: 'THRESHOLD_REACHED',
    INTERNAL_ERROR: 'INTERNAL_ERROR',
  },
};
